#!/bin/sh

prefix=/mnt/luna/fridge2_rawdata/Nafen_cell
data=.

if [ ! -d "$prefix" ]; then 
  printf "Data folder is not avalable: $prefix";
  exit 1
fi

while read f d c; do
  [ "$f" != "#" ] || continue
  name=$(echo $f | sed 's|/|_|g')
  echo $name
  ./process_flopper_dacfile --points 50 --round_freq 0.1 $prefix/$f $d > $name.dat
done < data_run1.tab

