#!/bin/sh

prefix=/mnt/luna/fridge2_rawdata/Nafen_cell
data=.

if [ ! -d "$prefix" ]; then
  printf "Data folder is not avalable: $prefix";
  exit 1
fi

while read f d c; do
  [ "$f" != "#" ] || continue
  name=$(echo $f | sed 's|/|_|g')
  echo $name
  ./process_flopper_dacfile --split_n 1 --points 50  $prefix/$f $d > $data/5m_$name.dat
done < data_run5.tab
