#!/usr/bin/python3

import numpy
import argparse
from icta import interp_icta

################################
# Add ICTA width as 9-th column

parser = argparse.ArgumentParser()
parser.add_argument('infile')
parser.add_argument('outfile')

parser.add_argument('--icta_plot', default='',
                    help='plot ICTA data to a png file')

parser.add_argument('--sm_win', default=21, type=int,
                    help='window for data smoothing')

parser.add_argument('--skip', default='',
                    help='skip points (1-2,30-40,5)')

args = parser.parse_args()

# load data
data = numpy.loadtxt(args.infile, comments='#', unpack=True, usecols=range(0,8))


# skip data points
n = len(data[0])
mask = numpy.ones(n, dtype=bool)
for r in args.skip.split(','):
  a = r.split('-')
  if len(a) == 0 or a[0] == '': continue
  if len(a) == 1:
    mask[int(a[0])]=False
  else:
    if a[1] == '': a[1] = n
    mask[range(int(a[0]),int(a[1]))] = False

if not numpy.all(mask):
  data = data[:,mask]
  n = data[0].size


# load ICTA data for the whole time range
icta = interp_icta(data[0], win=args.sm_win, marg=30, plot=args.icta_plot)


# save file
numpy.savetxt(args.outfile, numpy.column_stack((numpy.transpose(data),icta)),
  header = "time -- freq -- drive offs -- drive amp -- phase -- amp1 -- amp2 -- amp 3 -- icta",
  fmt='%.6f %f  %e %e %e  %e %e %e %e')

