#!/bin/sh

echo "
# ../res_1m/RUN5_DM1_flopper_AC_5A.dat                  11 R05D01a_5A
# ../res_1m/RUN5_DM1_flopper_Fsweep_5A.dat               1 R05D01b_5A  S 50 0.01 1
# ../res_1m/RUN5_DM2_flopper_AC_1Hz_5A.dat              21 R05D02a_5A
# ../res_5m/RUN5_DM3_flopper_AC_1Hz_2p5A_amp_sweep.dat   1 R05D03a_5A
# ../res_5m/RUN5_DM3_flopper_AC_1Hz_2p5A.dat            5 R05D03b_5A
# ../res_1m/RUN5_DM3_flopper_AC_1Hz_4A.dat              21 R05D03c_4A
# ../res_5m/RUN5_DM3_flopper_AC_1Hz_5p8A.dat            21 R05D03d_8A
# ../res_1m/RUN5_DM4_flopper_4Hz_2p5A.dat                11 R05D04a_5A  S 0.1 0.01 1
# ../res_1m/RUN5_DM4_flopper_amp_sweep4A.dat            21 R05D04b_4A  S 0.1 0.005 2 # use S 0.1 0.005 2 to split all
# ../res_5m/RUN5_DM5_flopper_2Hz_2p0A.dat               21 R05D05a_0A S 0.1 0.005
# ../res_1m/RUN5_DM5_flopper_2Hz_5p8A.dat               21 R05D05b_8A  S 0.1 0.005
# ../res_1m/RUN5_DM6_flopper_2Hz_2p8A.dat               21 R05D06a_8A  S 0.1 0.008
# ../res_1m/RUN5_DM6_flopper_2Hz_5p8A.dat               21 R05D06b_8A  S 0.1 0.002
# ../res_5m/RUN5_DM7_flopper_3Hz_3A_AmpSweep.dat        21 R05D07a_3A  S 0.1 0.004
# ../res_5m/RUN5_DM7_flopper_3Hz_5p2A_AmpSweep.dat      41 R05D07b_2A  S 0.1 0.002
" |
while read file win pref action arg1 arg2 arg3 comm; do
  [ -f "$file" ] || continue
  echo "$file -- $win -- $pref -- $action"
  ./add_icta $file $pref.dat --sm_win $win --icta_plot ${pref}_icta.png

  if [ "$action" = 'S' ]; then
    ./split_files $pref.dat "$pref%0${arg3}d.dat" --fstep "$arg1" --dstep "$arg2"
    rm -f $pref.dat
  fi

done