#!/usr/bin/python3

import math
import numpy
import matplotlib.pyplot as plt


fig, ax = plt.subplots(2,1, figsize=(5, 8))

###############

def plot_file(f, c, l):
  time, freq, doffs, damp, phase, amp1, amp2, amp3, icta =\
    numpy.loadtxt(f + '.dat', comments='#', unpack=True, usecols=range(0,9))
  phase = numpy.mod(phase,2*math.pi)
  ax[0].plot(freq, amp1, c, label = l)
  ax[1].plot(freq, phase,     c, label = l)

###############

plot_file('R05D01b_5A_04Hz_24mV', 'r*-', '24mV')
plot_file('R05D01b_5A_08Hz_48mV', 'b*-', '48mV')


###############

ax[0].set_ylabel('amp1/drive')
ax[1].set_ylabel('phase, rad')
ax[1].set_xlabel('Frequency, Hz')
ax[0].legend()
plt.savefig('R05D01b_5A_plot.png')
