#!/usr/bin/python3

import numpy
import math
import matplotlib.pyplot as plt


fig, ax = plt.subplots(2,1, figsize=(5, 8))

###########

def plot_file(f, c, l):
  time, freq, doffs, damp, phase, amp1, amp2, amp3, icta =\
    numpy.loadtxt(f + '.dat', comments='#', unpack=True, usecols=range(0,9))
  phase[phase>3] -= 2*math.pi
  ax[0].plot(icta, amp1/damp, c, label = l, markersize = 1)
  ax[1].plot(icta, phase,     c, label = l, markersize = 1)


###########

plot_file('R05D04b_4A_01Hz_15mV', 'r.', '1Hz 15mV')
plot_file('R05D04b_4A_01Hz_24mV', 'g.', '1Hz 24mV')
plot_file('R05D04b_4A_01Hz_30mV', 'b.', '1Hz 30mV')
plot_file('R05D04b_4A_01Hz_38mV', 'm.', '1Hz 38mV')
plot_file('R05D04b_4A_01Hz_45mV', 'c.', '1Hz 45mV')
ax[0].text(600, 3.8, '1Hz')
ax[1].text(600, 1.6, '1Hz')

plot_file('R05D04b_4A_02Hz_10mV', 'r.', '2Hz 10m')
plot_file('R05D04b_4A_02Hz_15mV', 'g.', '2Hz 15m')
plot_file('R05D04b_4A_02Hz_20mV', 'b.', '2Hz 20m')
plot_file('R05D04b_4A_02Hz_24mV', 'm.', '2Hz 24m')
plot_file('R05D04b_4A_02Hz_30mV', 'c.', '2Hz 30m')
ax[0].text(600, 1.9, '2Hz')
ax[1].text(600, 0.6, '2Hz')

plot_file('R05D04b_4A_03Hz_10mV', 'r.', '3Hz 10mV')
plot_file('R05D04b_4A_03Hz_15mV', 'g.', '3Hz 15mV')
plot_file('R05D04b_4A_03Hz_20mV', 'b.', '3Hz 20mV')
plot_file('R05D04b_4A_03Hz_24mV', 'm.', '3Hz 24mV')
plot_file('R05D04b_4A_03Hz_30mV', 'c.', '3Hz 30mV')
ax[0].text(600, 0.8, '3Hz')
ax[1].text(600, -0.2, '3Hz')

plot_file('R05D04b_4A_04Hz_10mV', 'r.', '4Hz 10mV')
plot_file('R05D04b_4A_04Hz_15mV', 'g.', '4Hz 15mV')
plot_file('R05D04b_4A_04Hz_20mV', 'b.', '4Hz 20mV')
plot_file('R05D04b_4A_04Hz_24mV', 'm.', '4Hz 24mV')
plot_file('R05D04b_4A_04Hz_30mV', 'c.', '4Hz 30mV')
ax[0].text(600, 0.1, '4Hz')
ax[1].text(600, -0.7, '4Hz')

###########

ax[0].set_ylabel('amp1/drive')
ax[1].set_ylabel('phase, rad')
ax[1].set_xlabel('ICTA width, Hz')
plt.savefig('R05D04b_4A_plot.png')
