#!/usr/bin/python3

import numpy
import math
import matplotlib.pyplot as plt


fig, ax = plt.subplots(2,1, figsize=(5, 8))

def plot_file(f, c, l):
  time, freq, doffs, damp, phase, amp1, amp2, amp3, icta =\
    numpy.loadtxt(f + '.dat', comments='#', unpack=True, usecols=range(0,9))
  phase[phase<0] += 2*math.pi
  ax[0].plot(icta, amp1/damp, c, label = l, markersize = 4, linewidth=0.5)
  ax[1].plot(icta, phase,     c, label = l, markersize = 4, linewidth=0.5)

###########

plot_file('R05D08_5p0A_2Hz_05mV', 'r.-', '2 Hz, 05 mV')
plot_file('R05D08_5p0A_2Hz_10mV', 'g.-', '2 Hz, 10 mV')
plot_file('R05D08_5p0A_2Hz_30mV', 'b.-', '2 Hz, 30 mV')

###########

ax[0].set_ylabel('amp1/drive')
ax[1].set_ylabel('phase, rad')
ax[1].set_xlabel('ICTA width, Hz')
ax[0].legend()
plt.savefig('R05D08_5p0A_2Hz_plot.png')
