#!/bin/sh

prefix=/mnt/luna/fridge2_rawdata/Nafen_cell

mkdir -p data_1m
while read f d c; do
  [ "$f" != "#" ] || continue
  name=$(echo $f | sed 's|/|_|g')
  echo $name
  ./process_flopper_dacfile --split_n 1 --points 50 --round_freq 0.1 $prefix/$f $d > data_1m/$name.dat
done < datafolders.txt
