#!/usr/bin/python3

import numpy
import math
import matplotlib.pyplot as plt


fig, ax = plt.subplots(2,1, figsize=(5, 8))

###########

def plot_file(f, c, l):
  time, freq, doffs, damp, phase, amp1, amp2, amp3, icta =\
    numpy.loadtxt(f + '.dat', comments='#', unpack=True, usecols=range(0,9))
  phase[phase<0] += 2*math.pi
  ax[0].plot(icta, amp1/damp, c, label = l, markersize = 1)
  ax[1].plot(icta, phase,     c, label = l, markersize = 1)

###########

plot_file('R05D01a_5p0A', 'r.', 'R05D01a_5p0A')
plot_file('R05D02a_5p0A', 'b.', 'R05D02a_5p0A')
plot_file('R05D03b_2p5A', 'g.', 'R05D03b_2p5A')
plot_file('R05D03c_4p0A', 'm.', 'R05D03c_4p0A')
plot_file('R05D03d_5p8A', 'c.', 'R05D03d_5p8A')

###########

ax[0].set_ylabel('amp1/drive')
ax[1].set_ylabel('phase, rad')
ax[1].set_xlabel('ICTA width, Hz')
ax[0].legend()
plt.savefig('plot_temp_sweep1.png')
