#!/usr/bin/python3

import numpy
import math
import matplotlib.pyplot as plt


fig, ax = plt.subplots(2,1, figsize=(5, 8))

def plot_file(f, c, l):
  time, freq, doffs, damp, phase, amp1, amp2, amp3, icta =\
    numpy.loadtxt(f + '.dat', comments='#', unpack=True, usecols=range(0,9))
  phase[phase<0] += 2*math.pi
  ax[0].plot(icta, amp1/damp, c, label = l, markersize = 4, linewidth=0.5)
  ax[1].plot(icta, phase,     c, label = l, markersize = 4, linewidth=0.5)

###########

plot_file('R05D09_4p5A_4Hz_06mV', 'r.-', '4 Hz, 06 mV')
plot_file('R05D09_4p5A_4Hz_12mV', 'g.-', '4 Hz, 12 mV')
plot_file('R05D09_4p5A_4Hz_22mV', 'b.-', '4 Hz, 22 mV')
plot_file('R05D09_4p5A_4Hz_28mV', 'c.-', '4 Hz, 28 mV')
plot_file('R05D09_4p5A_4Hz_33mV', 'm.-', '4 Hz, 33 mV')

###########

ax[0].set_ylabel('amp1/drive')
ax[1].set_ylabel('phase, rad')
ax[1].set_xlabel('ICTA width, Hz')
ax[0].legend()
plt.savefig('R05D09_4p5A_4Hz_plot.png')
