#!/usr/bin/python3

import math
import numpy
import matplotlib.pyplot as plt


fig, ax = plt.subplots(2,1, figsize=(5, 8))

###########

def plot_file(f, c, l):
  time, freq, doffs, damp, phase, amp1, amp2, amp3, icta =\
    numpy.loadtxt(f + '.dat', comments='#', unpack=True, usecols=range(0,9))
  phase[phase<0] += 2*math.pi
  ax[0].plot(damp, amp1, c, label = l)
  ax[1].plot(damp, phase,     c, label = l)

#################

plot_file('R05D03a_2p5A', 'r*', 'R05D03a_2p5A')

#################

ax[0].set_ylabel('amp1')
ax[1].set_ylabel('phase, rad')
ax[1].set_xlabel('Recorded drive amplitude, V')
ax[0].legend()
plt.savefig('R05D03a_2p5A_plot.png')
