#!/usr/bin/python3

import numpy
import math
import scipy.optimize
import scipy.integrate
import matplotlib.pyplot as plt
from non_lin_osc import *


w0 = 1
tau = 0.5
vc = 1
k = 0.7
F = numpy.array([0.5,1,2,3,4])
w = numpy.linspace(0.1,2,100)


for fi in range(F.size):
  amp = numpy.zeros(w.size)
  ph  = numpy.zeros(w.size)
  for wi in range(w.size):
    uv = nonlin_osc_solve0(w[wi],F[fi], osc_pseudopl1, [w0,tau,vc,k], [0,0])
    amp[wi] = numpy.hypot(uv[0],uv[1])/F[fi]
    ph[wi]  = numpy.arctan2(uv[1],uv[0])

  plt.plot(w, amp, label=F[fi])

plt.xlabel('frequency')
plt.ylabel('amplitude/drive')
plt.legend()
plt.savefig('solve_avrg.png')
